//==============================================================================
// TorqueLab ->
// Copyright (c) 2015 All Right Reserved, http://nordiklab.com/
//------------------------------------------------------------------------------
//==============================================================================
//==============================================================================
// Material Update Functionality
$Pref::MaterialEditorGui::DefaultMaterialFile = "art/materials.cs";
function MaterialEditorGui::saveDialogCancel( %this ) {
	MaterialEditorGui.guiSync( materialEd_previewMaterial );
}
//------------------------------------------------------------------------------
//==============================================================================
function MaterialEditorGui::saveDialogDontSave( %this, %material ) {
	MaterialEditorGui.currentMaterial.setName( %this.originalName );
	//restore to defaults
	MaterialEditorGui.copyMaterials( notDirtyMaterial, MaterialEditorGui.currentMaterial );
	MaterialEditorGui.copyMaterials( notDirtyMaterial, materialEd_previewMaterial );
	MaterialEditorGui.guiSync( materialEd_previewMaterial );
	materialEd_previewMaterial.flush();
	materialEd_previewMaterial.reload();
	MaterialEditorGui.currentMaterial.flush();
	MaterialEditorGui.currentMaterial.reload();
	MaterialEditorGui.setMaterialNotDirty();
	MaterialEditorGui.setActiveMaterial( %material );
}
//------------------------------------------------------------------------------
//==============================================================================
function MaterialEditorGui::saveDialogSave( %this, %material ) {
	MaterialEditorGui.save();
	MaterialEditorGui.setActiveMaterial( %material );
}
//------------------------------------------------------------------------------
//==============================================================================
function MaterialEditorGui::save( %this,%material,%external ) {
	%mat = MaterialEditorGui.currentMaterial;

	if (!isObject(%mat))
		return;

	if( %mat.getName() $= "" ) {
		LabMsgOK("Cannot perform operation", "Saved materials cannot be named \"\". A name must be given before operation is performed" );
		return;
	}

	// Update the live object regardless in this case
	MaterialEditorGui.updateLivePreview(true);

	// Specifically for materials autogenerated from shapes.
	if( %mat.isAutoGenerated() )
		%mat.setAutoGenerated( false );

	// Save the material using the persistence manager
	matEd_PersistMan.saveDirty();
	// Clean up the Material Editor
	MaterialEditorGui.copyMaterials( materialEd_previewMaterial, notDirtyMaterial );
	MaterialEditorGui.setMaterialNotDirty();
}
//------------------------------------------------------------------------------

//==============================================================================
function MaterialEditorGui::setMaterialNotDirty(%this) {
	%propertyText = "Material Properties";
	%previewText = "Material Preview";
	MaterialEditorPropertiesWindow.text = %propertyText;
	MaterialEditorPreviewWindow.text = %previewText;
	MaterialEditorPropertiesWindow-->quickSaveButton.active = 0;
	MaterialEditorGui.materialDirty = false;
	matEd_PersistMan.removeDirty(MaterialEditorGui.currentMaterial);
}
//------------------------------------------------------------------------------
//==============================================================================
function MaterialEditorGui::setMaterialDirty(%this) {
	%propertyText = "Material Properties *";
	%previewText = "Material Preview *";
	MaterialEditorPropertiesWindow.text = %propertyText;
	MaterialEditorPreviewWindow.text = %previewText;
	MaterialEditorGui.materialDirty = true;
	MaterialEditorPropertiesWindow-->quickSaveButton.active = 1;

	// materials created in the material selector are given that as its filename, so we run another check
	if( MaterialEditorGui.isMatEditorMaterial( MaterialEditorGui.currentMaterial ) ) {
		if( MaterialEditorGui.currentMaterial.isAutoGenerated() ) {
			%obj = MaterialEditorGui.currentObject;

			if( %obj.shapeName !$= "" )
				%shapePath = %obj.shapeName;
			else if( %obj.isMethod("getDatablock") ) {
				if( %obj.getDatablock().shapeFile !$= "" )
					%shapePath = %obj.getDatablock().shapeFile;
			}

			//creating toPath
			%k = 0;

			while( strpos( %shapePath, "/", %k ) != -1 ) {
				%pos = strpos( %shapePath, "/", %k );
				%k = %pos + 1;
			}

			%savePath = getSubStr( %shapePath , 0 , %k );
			%savePath = %savePath @ "materials.cs";
			matEd_PersistMan.setDirty(MaterialEditorGui.currentMaterial, %savePath);
		} else {
			matEd_PersistMan.setDirty(MaterialEditorGui.currentMaterial, "art/materials.cs");
		}
	} else
		matEd_PersistMan.setDirty(MaterialEditorGui.currentMaterial);
}
//------------------------------------------------------------------------------

//==============================================================================
function MaterialEditorGui::showSaveDialog( %this, %toMaterial ) {
	LabMsgYesNoCancel("Save Material?",
							"The material " @ MaterialEditorGui.currentMaterial.getName() @ " has unsaved changes. <br>Do you want to save?",
							"MaterialEditorGui.saveDialogSave(" @ %toMaterial @ ");",
							"MaterialEditorGui.saveDialogDontSave(" @ %toMaterial @ ");",
							"MaterialEditorGui.saveDialogCancel();" );
}
//------------------------------------------------------------------------------
//==============================================================================
function MaterialEditorGui::showMaterialChangeSaveDialog( %this, %toMaterial ) {
	%fromMaterial = MaterialEditorGui.currentMaterial;
	LabMsgYesNoCancel("Save Material?",
							"The material " @ %fromMaterial.getName() @ " has unsaved changes. <br>Do you want to save before changing the material?",
							"MaterialEditorGui.saveDialogSave(" @ %toMaterial @ "); MaterialEditorGui.changeMaterial(" @ %fromMaterial @ ", " @ %toMaterial @ ");",
							"MaterialEditorGui.saveDialogDontSave(" @ %toMaterial @ "); MaterialEditorGui.changeMaterial(" @ %fromMaterial @ ", " @ %toMaterial @ ");",
							"MaterialEditorGui.saveDialogCancel();" );
}
//------------------------------------------------------------------------------