$TLab_AutoSaveDelay = "5";
$TLab_AutoSaveEnabled = "1";
$TLab_Class_Inspector_LogLevel = 0;
$TLab_defaultGui = "MainMenuGui";
$TLab_ImageExtensions = "png dds jpg jpeg bmp tga";
$TLab_Object_DropTypes = "atOrigin atCamera atCameraRot belowCamera screenCenter atCentroid toTerrain belowSelection";
$TLab_PrefabAutoMode = "Level Object Folder";
$TLab_Theme = "DarkLab";
$TLab_ThemePath = "tlab/themes/DarkLab/";
